dubbo:
  application:
    name: cls-service
  registry:
    address: zookeeper://192.168.57.188:2181
  protocol:
    #自动查找一个可用的端口，默认是20880
    port: -1
spring:
  datasource:
    url: jdbc:mysql:///sbd?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

